/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package transittrace;

/**
 *
 * @author Harsha
 */
public class QuizGUI extends javax.swing.JFrame {

    /**
     * Creates new form QuizGUI
     */
    private String Answer;
    private int i;
    private int difficulty;
    public QuizGUI() {
        initComponents();
        QuestionLbl.setVisible(false);
        option1Btn.setVisible(false);
        option2Btn.setVisible(false);
        option3Btn.setVisible(false);
        option4Btn.setVisible(false);
        SubmitBtn.setVisible(false);
        answerLbl.setVisible(false);
        FactLbl.setVisible(false);
        i=0;
        difficulty=0;
        Answer="";
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeGrp = new javax.swing.ButtonGroup();
        exitButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        easyBtn = new javax.swing.JButton();
        mediumBtn = new javax.swing.JButton();
        hardBtn = new javax.swing.JButton();
        extremeBtn = new javax.swing.JButton();
        option1Btn = new javax.swing.JRadioButton();
        option2Btn = new javax.swing.JRadioButton();
        option3Btn = new javax.swing.JRadioButton();
        option4Btn = new javax.swing.JRadioButton();
        QuestionLbl = new javax.swing.JLabel();
        SubmitBtn = new javax.swing.JButton();
        answerLbl = new javax.swing.JLabel();
        FactLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitButton.setText("Return to Home");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 6, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Choose the Difficulty: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 101, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Quiz");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 35, -1, -1));

        easyBtn.setText("easy");
        easyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyBtnActionPerformed(evt);
            }
        });
        getContentPane().add(easyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 111, -1, -1));

        mediumBtn.setText("medium");
        mediumBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumBtnActionPerformed(evt);
            }
        });
        getContentPane().add(mediumBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 111, -1, -1));

        hardBtn.setText("hard");
        hardBtn.setToolTipText("");
        hardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardBtnActionPerformed(evt);
            }
        });
        getContentPane().add(hardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 111, -1, -1));

        extremeBtn.setText("Extreme");
        extremeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extremeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(extremeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(637, 111, -1, -1));

        typeGrp.add(option1Btn);
        option1Btn.setText("option 1");
        option1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                option1BtnActionPerformed(evt);
            }
        });
        getContentPane().add(option1Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 255, -1, -1));

        typeGrp.add(option2Btn);
        option2Btn.setText("option 2");
        getContentPane().add(option2Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 294, -1, -1));

        typeGrp.add(option3Btn);
        option3Btn.setText("option 3");
        getContentPane().add(option3Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 333, -1, -1));

        typeGrp.add(option4Btn);
        option4Btn.setText("option 4");
        getContentPane().add(option4Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 372, -1, -1));

        QuestionLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        QuestionLbl.setText("Present the question");
        getContentPane().add(QuestionLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 205, -1, -1));

        SubmitBtn.setText("Submit");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(637, 399, -1, -1));

        answerLbl.setText("Answer");
        getContentPane().add(answerLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 472, -1, -1));

        FactLbl.setText("Fact");
        getContentPane().add(FactLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 533, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void option1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_option1BtnActionPerformed
        
    }//GEN-LAST:event_option1BtnActionPerformed


    private void easyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyBtnActionPerformed
        answerLbl.setVisible(false);
        FactLbl.setVisible(false);
        Easy e=new Easy();
        
        difficulty=1;
        i=(int)(Math.random()*3);
        e.setRandomNumber(i);
        QuestionLbl.setText(e.getQuestion());
        
        option1Btn.setText(e.getOptions1());
        option2Btn.setText(e.getOptions2());
        option3Btn.setText(e.getOptions3());
        option4Btn.setText(e.getOptions4());
        QuestionLbl.setVisible(true);
        option1Btn.setVisible(true);
        option2Btn.setVisible(true);
        option3Btn.setVisible(true);
        option4Btn.setVisible(true);
        SubmitBtn.setVisible(true);
    }//GEN-LAST:event_easyBtnActionPerformed

    private void mediumBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumBtnActionPerformed
        answerLbl.setVisible(false);
        FactLbl.setVisible(false);
        difficulty=2;
        Medium m=new Medium();
        i=(int)(Math.random()*3);
        m.setRandomNumber(i);
        QuestionLbl.setText(m.getQuestion());
        
        option1Btn.setText(m.getOptions1());
        option2Btn.setText(m.getOptions2());
        option3Btn.setText(m.getOptions3());
        option4Btn.setText(m.getOptions4());
        
        
        
        QuestionLbl.setVisible(true);
        option1Btn.setVisible(true);
        option2Btn.setVisible(true);
        option3Btn.setVisible(true);
        option4Btn.setVisible(true);
        SubmitBtn.setVisible(true);
    }//GEN-LAST:event_mediumBtnActionPerformed

    private void hardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardBtnActionPerformed
        answerLbl.setVisible(false);
        FactLbl.setVisible(false);
        difficulty=3;
        Hard h=new Hard();
        i=(int)(Math.random()*3);
        h.setRandomNumber(i);
        QuestionLbl.setText(h.getQuestion());
        
        option1Btn.setText(h.getOptions1());
        option2Btn.setText(h.getOptions2());
        option3Btn.setText(h.getOptions3());
        option4Btn.setText(h.getOptions4());
        
        
        
        QuestionLbl.setVisible(true);
        option1Btn.setVisible(true);
        option2Btn.setVisible(true);
        option3Btn.setVisible(true);
        option4Btn.setVisible(true);
        SubmitBtn.setVisible(true);
    }//GEN-LAST:event_hardBtnActionPerformed

    private void extremeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extremeBtnActionPerformed
        answerLbl.setVisible(false);
        FactLbl.setVisible(false);
        difficulty=4;
        Extreme E=new Extreme();
        i=(int)(Math.random()*3);
        E.setRandomNumber(i);
        QuestionLbl.setText(E.getQuestion());
        
        option1Btn.setText(E.getOptions1());
        option2Btn.setText(E.getOptions2());
        option3Btn.setText(E.getOptions3());
        option4Btn.setText(E.getOptions4());
        
        
        
        QuestionLbl.setVisible(true);
        option1Btn.setVisible(true);
        option2Btn.setVisible(true);
        option3Btn.setVisible(true);
        option4Btn.setVisible(true);
        SubmitBtn.setVisible(true);
    }//GEN-LAST:event_extremeBtnActionPerformed

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed

        Easy e=new Easy();
        Medium m=new Medium();
        Hard h=new Hard();
        Extreme E=new Extreme();
        
        if(difficulty==1){
            e.setRandomNumber(i);
            if(option1Btn.isSelected()){
                Answer=e.getOptions1();
                
            }
            else if(option2Btn.isSelected()){
                Answer=e.getOptions2();
            }
            else if(option3Btn.isSelected()){
                Answer=e.getOptions3();
            }
            else if(option4Btn.isSelected()){
                Answer=e.getOptions4();
            }
        }
        else if(difficulty==2){
            m.setRandomNumber(i);
            if(option1Btn.isSelected()){
                Answer=m.getOptions1();
                
            }
            else if(option2Btn.isSelected()){
                Answer=m.getOptions2();
            }
            else if(option3Btn.isSelected()){
                Answer=m.getOptions3();
            }
            else if(option4Btn.isSelected()){
                Answer=m.getOptions4();
            }
        }
        else if(difficulty==3){
            h.setRandomNumber(i);
            if(option1Btn.isSelected()){
                Answer=h.getOptions1();
                
            }
            else if(option2Btn.isSelected()){
                Answer=h.getOptions2();
            }
            else if(option3Btn.isSelected()){
                Answer=h.getOptions3();
            }
            else if(option4Btn.isSelected()){
                Answer=h.getOptions4();
            }
        }
        else if(difficulty==4){
            E.setRandomNumber(i);
            if(option1Btn.isSelected()){
                Answer=E.getOptions1();
                
            }
            else if(option2Btn.isSelected()){
                Answer=E.getOptions2();
            }
            else if(option3Btn.isSelected()){
                Answer=E.getOptions3();
            }
            else if(option4Btn.isSelected()){
                Answer=E.getOptions4();
            }
        }
        
        if(difficulty==1){
            e.setRandomNumber(i);
            if(Answer.equals(e.getAnswer())){
                answerLbl.setText("The answer you Have Selected is correct");
                FactLbl.setText(e.getFact());
                answerLbl.setVisible(true);
                FactLbl.setVisible(true);
         
            }
            else{
                answerLbl.setText("The answer you Have Selected is wrong the correct answer is "+e.getAnswer());
                FactLbl.setText(e.getFact());
                answerLbl.setVisible(true);
                FactLbl.setVisible(true);
        
                
            }
            
        }
        
        else if(difficulty==2){
            m.setRandomNumber(i);
            if(Answer.equals(m.getAnswer())){
                answerLbl.setText("The answer you Have Selected is correct");
                FactLbl.setText(m.getFact());
                answerLbl.setVisible(true);
                FactLbl.setVisible(true);
            }
            else{
                answerLbl.setText("The answer you Have Selected is wrong the correct answer is "+m.getAnswer());
                FactLbl.setText(m.getFact());
                answerLbl.setVisible(true);
                FactLbl.setVisible(true);
            }
            
        }
                
        else if(difficulty==3){
            h.setRandomNumber(i);
            if(Answer.equals(h.getAnswer())){
                answerLbl.setText("The answer you Have Selected is correct");
                FactLbl.setText(h.getFact());
                answerLbl.setVisible(true);
                FactLbl.setVisible(true);
            }
            else{
                answerLbl.setText("The answer you Have Selected is wrong the correct answer is "+h.getAnswer());
                FactLbl.setText(h.getFact());
                answerLbl.setVisible(true);
                FactLbl.setVisible(true);
            }
           
        }
        else if(difficulty==4){
            E.setRandomNumber(i);
            if(Answer.equals(E.getAnswer())){
                answerLbl.setText("The answer you Have Selected is correct");
                FactLbl.setText(E.getFact());
                answerLbl.setVisible(true);
                FactLbl.setVisible(true);
        
            }
            else{
                answerLbl.setText("The answer you Have Selected is wrong the correct answer is "+E.getAnswer());
                FactLbl.setText(E.getFact());
                answerLbl.setVisible(true);
                FactLbl.setVisible(true);
        
            }
           
        }
        
        
        
        
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_exitButtonActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FactLbl;
    private javax.swing.JLabel QuestionLbl;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JLabel answerLbl;
    private javax.swing.JButton easyBtn;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton extremeBtn;
    private javax.swing.JButton hardBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton mediumBtn;
    private javax.swing.JRadioButton option1Btn;
    private javax.swing.JRadioButton option2Btn;
    private javax.swing.JRadioButton option3Btn;
    private javax.swing.JRadioButton option4Btn;
    private javax.swing.ButtonGroup typeGrp;
    // End of variables declaration//GEN-END:variables
}
