package transittrace;

public class TransitTraceGUI extends javax.swing.JFrame {

    /**
     * Creates new form TransitTraceGUI
     */
    public TransitTraceGUI() {
        initComponents();
        marketplacePnl.setVisible(false);
        quizPnl.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPnl = new javax.swing.JPanel();
        homeButtonPnl = new javax.swing.JPanel();
        homeLbl = new javax.swing.JLabel();
        marketplaceButtonPnl = new javax.swing.JPanel();
        marketplaceLbl = new javax.swing.JLabel();
        quizButtonPnl = new javax.swing.JPanel();
        quizLbl = new javax.swing.JLabel();
        logoButtonPnl = new javax.swing.JPanel();
        logoLbl = new javax.swing.JLabel();
        homePnl = new javax.swing.JPanel();
        homeTitleLbl = new javax.swing.JLabel();
        carBtn = new javax.swing.JToggleButton();
        busBtn = new javax.swing.JToggleButton();
        metroBtn = new javax.swing.JToggleButton();
        motorbikeBtn = new javax.swing.JToggleButton();
        tramBtn = new javax.swing.JToggleButton();
        trainBtn = new javax.swing.JToggleButton();
        eMobilityBtn = new javax.swing.JToggleButton();
        instructionLbl = new javax.swing.JLabel();
        nextBtn = new javax.swing.JButton();
        carSpnr = new javax.swing.JSpinner();
        busSpnr = new javax.swing.JSpinner();
        metroSpnr = new javax.swing.JSpinner();
        eMobilitySpnr = new javax.swing.JSpinner();
        motorbikeSpnr = new javax.swing.JSpinner();
        tramSpnr = new javax.swing.JSpinner();
        trainSpnr = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        marketplacePnl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        wBottleLbl = new javax.swing.JLabel();
        binLbl = new javax.swing.JLabel();
        tBrushLbl = new javax.swing.JLabel();
        chargerLbl = new javax.swing.JLabel();
        coffeeLbl = new javax.swing.JLabel();
        coffeeCupLbl = new javax.swing.JLabel();
        cuttleryLbl = new javax.swing.JLabel();
        fWashLbl = new javax.swing.JLabel();
        jeansLbl = new javax.swing.JLabel();
        jewelryLbl = new javax.swing.JLabel();
        lightLbl = new javax.swing.JLabel();
        nBooksLbl = new javax.swing.JLabel();
        shirtLbl = new javax.swing.JLabel();
        sBagLbl = new javax.swing.JLabel();
        trashBagsLbl = new javax.swing.JLabel();
        cartLbl = new javax.swing.JLabel();
        bottleTitleLbl = new javax.swing.JLabel();
        bottleAdd = new javax.swing.JRadioButton();
        bottleDesLbl = new javax.swing.JLabel();
        bottlePriceLbl = new javax.swing.JLabel();
        toothTitlLbl = new javax.swing.JLabel();
        toothDesTitle = new javax.swing.JLabel();
        toothDesLbl = new javax.swing.JLabel();
        toothAdd = new javax.swing.JRadioButton();
        coffeeTitleLbl = new javax.swing.JLabel();
        coffeeDes1Lbl = new javax.swing.JLabel();
        coffeePrice = new javax.swing.JLabel();
        coffeeAdd = new javax.swing.JRadioButton();
        coffeeDes2 = new javax.swing.JLabel();
        cutleryTitleLbl = new javax.swing.JLabel();
        cutleryDesLbl = new javax.swing.JLabel();
        cutleryPrice = new javax.swing.JLabel();
        cutleryAdd = new javax.swing.JRadioButton();
        cutleryTitleLbl1 = new javax.swing.JLabel();
        jeansDes1Lbl = new javax.swing.JLabel();
        jeansPrice = new javax.swing.JLabel();
        jeansAdd = new javax.swing.JRadioButton();
        jeansDes2Lbl = new javax.swing.JLabel();
        lightTitleLbl = new javax.swing.JLabel();
        lightDes1Lbl = new javax.swing.JLabel();
        lightDes2Lbl = new javax.swing.JLabel();
        lightPrice = new javax.swing.JLabel();
        lightAdd = new javax.swing.JRadioButton();
        sBagTitlLbl = new javax.swing.JLabel();
        sBagDes1Lbl = new javax.swing.JLabel();
        sBagDes2Lbl = new javax.swing.JLabel();
        sBagPrice = new javax.swing.JLabel();
        sBagAdd = new javax.swing.JRadioButton();
        noteBookTitleLbl = new javax.swing.JLabel();
        noteBookDes1Lbl = new javax.swing.JLabel();
        noteBookDes2Lbl = new javax.swing.JLabel();
        noteBookPrice = new javax.swing.JLabel();
        noteBookAdd = new javax.swing.JRadioButton();
        fWashTitleLbl = new javax.swing.JLabel();
        fWashDes1Lbl = new javax.swing.JLabel();
        fWashDes2Lbl = new javax.swing.JLabel();
        fWashPrice = new javax.swing.JLabel();
        fWashAdd = new javax.swing.JRadioButton();
        jewelryTitleLbl = new javax.swing.JLabel();
        jewelryDes1Lbl = new javax.swing.JLabel();
        jewelryDes2Lbl = new javax.swing.JLabel();
        jewelryPrice = new javax.swing.JLabel();
        jewelryAdd = new javax.swing.JRadioButton();
        cCupTitleLbl = new javax.swing.JLabel();
        cCupDes1Lbl = new javax.swing.JLabel();
        cCupDes2Lbl = new javax.swing.JLabel();
        cCupPrice = new javax.swing.JLabel();
        cCupAdd = new javax.swing.JRadioButton();
        trashBagsTitleLbl = new javax.swing.JLabel();
        cCupDes1Lbl1 = new javax.swing.JLabel();
        trashBagsPrice = new javax.swing.JLabel();
        trashBagsAdd = new javax.swing.JRadioButton();
        chargerTitleLbl = new javax.swing.JLabel();
        chargerDes1Lbl = new javax.swing.JLabel();
        chargerPrice = new javax.swing.JLabel();
        chargerAdd = new javax.swing.JRadioButton();
        chargerDes2lbl = new javax.swing.JLabel();
        binAdd = new javax.swing.JRadioButton();
        binTitleLbl = new javax.swing.JLabel();
        binDes1Lbl = new javax.swing.JLabel();
        binDes2Lbl = new javax.swing.JLabel();
        binPrice = new javax.swing.JLabel();
        shirtTitleLbl = new javax.swing.JLabel();
        shirtDes1Lbl = new javax.swing.JLabel();
        shirtDes2Lbl = new javax.swing.JLabel();
        shirtPrice = new javax.swing.JLabel();
        shirtAdd = new javax.swing.JRadioButton();
        quizPnl = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));

        menuPnl.setBackground(new java.awt.Color(56, 178, 113));

        homeButtonPnl.setBackground(new java.awt.Color(165, 217, 183));
        homeButtonPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeButtonPnlMouseClicked(evt);
            }
        });

        homeLbl.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        homeLbl.setText("HOME");

        javax.swing.GroupLayout homeButtonPnlLayout = new javax.swing.GroupLayout(homeButtonPnl);
        homeButtonPnl.setLayout(homeButtonPnlLayout);
        homeButtonPnlLayout.setHorizontalGroup(
            homeButtonPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeButtonPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homeButtonPnlLayout.setVerticalGroup(
            homeButtonPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeButtonPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        marketplaceButtonPnl.setBackground(new java.awt.Color(165, 217, 183));
        marketplaceButtonPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marketplaceButtonPnlMouseClicked(evt);
            }
        });

        marketplaceLbl.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        marketplaceLbl.setText("MARKETPLACE");

        javax.swing.GroupLayout marketplaceButtonPnlLayout = new javax.swing.GroupLayout(marketplaceButtonPnl);
        marketplaceButtonPnl.setLayout(marketplaceButtonPnlLayout);
        marketplaceButtonPnlLayout.setHorizontalGroup(
            marketplaceButtonPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marketplaceButtonPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(marketplaceLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        marketplaceButtonPnlLayout.setVerticalGroup(
            marketplaceButtonPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marketplaceButtonPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(marketplaceLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        quizButtonPnl.setBackground(new java.awt.Color(165, 217, 183));
        quizButtonPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quizButtonPnlMouseClicked(evt);
            }
        });

        quizLbl.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        quizLbl.setText("QUIZ");

        javax.swing.GroupLayout quizButtonPnlLayout = new javax.swing.GroupLayout(quizButtonPnl);
        quizButtonPnl.setLayout(quizButtonPnlLayout);
        quizButtonPnlLayout.setHorizontalGroup(
            quizButtonPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quizButtonPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        quizButtonPnlLayout.setVerticalGroup(
            quizButtonPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quizButtonPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quizLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        logoButtonPnl.setBackground(new java.awt.Color(165, 217, 183));

        logoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transittrace/images/logo1.png"))); // NOI18N

        javax.swing.GroupLayout logoButtonPnlLayout = new javax.swing.GroupLayout(logoButtonPnl);
        logoButtonPnl.setLayout(logoButtonPnlLayout);
        logoButtonPnlLayout.setHorizontalGroup(
            logoButtonPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
        );
        logoButtonPnlLayout.setVerticalGroup(
            logoButtonPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout menuPnlLayout = new javax.swing.GroupLayout(menuPnl);
        menuPnl.setLayout(menuPnlLayout);
        menuPnlLayout.setHorizontalGroup(
            menuPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoButtonPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeButtonPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(marketplaceButtonPnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quizButtonPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuPnlLayout.setVerticalGroup(
            menuPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPnlLayout.createSequentialGroup()
                .addComponent(logoButtonPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(homeButtonPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(marketplaceButtonPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quizButtonPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        homePnl.setBackground(new java.awt.Color(55, 162, 179));

        homeTitleLbl.setText("CO2 Emissions Calculator");

        carBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transittrace/images/car.png"))); // NOI18N
        carBtn.setBorder(null);
        carBtn.setBorderPainted(false);
        carBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        carBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carBtnMouseClicked(evt);
            }
        });
        carBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carBtnActionPerformed(evt);
            }
        });

        busBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transittrace/images/bus.png"))); // NOI18N
        busBtn.setBorder(null);
        busBtn.setBorderPainted(false);
        busBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        metroBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transittrace/images/metro.png"))); // NOI18N
        metroBtn.setBorder(null);
        metroBtn.setBorderPainted(false);
        metroBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        metroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metroBtnActionPerformed(evt);
            }
        });

        motorbikeBtn.setForeground(new java.awt.Color(255, 255, 255));
        motorbikeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transittrace/images/motorbike.png"))); // NOI18N
        motorbikeBtn.setBorder(null);
        motorbikeBtn.setBorderPainted(false);
        motorbikeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tramBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transittrace/images/tram.png"))); // NOI18N
        tramBtn.setBorder(null);
        tramBtn.setBorderPainted(false);
        tramBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        trainBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transittrace/images/train.png"))); // NOI18N
        trainBtn.setBorder(null);
        trainBtn.setBorderPainted(false);
        trainBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        trainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainBtnActionPerformed(evt);
            }
        });

        eMobilityBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transittrace/images/eMobility.png"))); // NOI18N
        eMobilityBtn.setBorder(null);
        eMobilityBtn.setBorderPainted(false);
        eMobilityBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        eMobilityBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eMobilityBtnActionPerformed(evt);
            }
        });

        instructionLbl.setText("Choose your commute modes and the distance travelled in it");

        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        carSpnr.setEnabled(false);

        busSpnr.setEnabled(false);

        metroSpnr.setEnabled(false);

        eMobilitySpnr.setEnabled(false);

        motorbikeSpnr.setEnabled(false);

        tramSpnr.setEnabled(false);

        trainSpnr.setEnabled(false);

        jLabel1.setText("The total CO2 Emission for your commute is:");

        javax.swing.GroupLayout homePnlLayout = new javax.swing.GroupLayout(homePnl);
        homePnl.setLayout(homePnlLayout);
        homePnlLayout.setHorizontalGroup(
            homePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePnlLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(instructionLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(homePnlLayout.createSequentialGroup()
                .addGroup(homePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(homePnlLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(homeTitleLbl))
                    .addGroup(homePnlLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(homePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(homePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(homePnlLayout.createSequentialGroup()
                                    .addComponent(eMobilityBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(eMobilitySpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(homePnlLayout.createSequentialGroup()
                                    .addComponent(busBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(busSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tramBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(homePnlLayout.createSequentialGroup()
                                    .addComponent(metroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(metroSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(trainBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(homePnlLayout.createSequentialGroup()
                                    .addComponent(carBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(carSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(101, 101, 101)
                                    .addComponent(motorbikeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addGroup(homePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145))
                    .addGroup(homePnlLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(homePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homePnlLayout.createSequentialGroup()
                                .addComponent(trainSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(homePnlLayout.createSequentialGroup()
                                .addGroup(homePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(motorbikeSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tramSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        homePnlLayout.setVerticalGroup(
            homePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeTitleLbl)
                .addGap(30, 30, 30)
                .addComponent(instructionLbl)
                .addGap(18, 18, 18)
                .addGroup(homePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePnlLayout.createSequentialGroup()
                        .addGroup(homePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(carBtn)
                            .addComponent(motorbikeBtn)
                            .addGroup(homePnlLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(carSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(homePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homePnlLayout.createSequentialGroup()
                                .addGroup(homePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(busBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tramBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(homePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(metroBtn)
                                    .addComponent(trainBtn)))
                            .addGroup(homePnlLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(busSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(metroSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(homePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homePnlLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(eMobilityBtn))
                            .addGroup(homePnlLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(eMobilitySpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(homePnlLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(motorbikeSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(tramSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(trainSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(56, 56, 56))
        );

        marketplacePnl.setBackground(new java.awt.Color(55, 162, 179));

        jScrollPane1.setBackground(new java.awt.Color(55, 162, 179));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(55, 162, 179));

        wBottleLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bottle (1).png"))); // NOI18N

        binLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bins (1).png"))); // NOI18N

        tBrushLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tooth (1).png"))); // NOI18N

        chargerLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/charger (1).png"))); // NOI18N

        coffeeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coffee.png"))); // NOI18N

        coffeeCupLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coffeecup.png"))); // NOI18N

        cuttleryLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cutlery.png"))); // NOI18N

        fWashLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/facewash (1).png"))); // NOI18N

        jeansLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jeans (1).png"))); // NOI18N

        jewelryLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jewlery (1).png"))); // NOI18N

        lightLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/light (1).png"))); // NOI18N

        nBooksLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notebooks (1).png"))); // NOI18N

        shirtLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shirt (1).png"))); // NOI18N

        sBagLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shoppingbag (1).png"))); // NOI18N

        trashBagsLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trashbags.png"))); // NOI18N

        cartLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vector-shopping-cart-icon.png"))); // NOI18N

        bottleTitleLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bottleTitleLbl.setText("Reusable Water Bottle");

        bottleAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bottleAdd.setText("Add to cart");
        bottleAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottleAddActionPerformed(evt);
            }
        });

        bottleDesLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bottleDesLbl.setText("Reduce single-use plastic waste by using a durable, refillable water bottle.");

        bottlePriceLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bottlePriceLbl.setText("Price: 9.99");

        toothTitlLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        toothTitlLbl.setText("Bamboo Tooth Brush");

        toothDesTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        toothDesTitle.setText("An eco-friendly alternative to plastic toothbrushes.");

        toothDesLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        toothDesLbl.setText("Price: 4.99");

        toothAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        toothAdd.setText("Add to cart");
        toothAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toothAddActionPerformed(evt);
            }
        });

        coffeeTitleLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        coffeeTitleLbl.setText("Fair Trade Coffee");

        coffeeDes1Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        coffeeDes1Lbl.setText("Coffee produced under fair trade conditions, ensuring fair wages and");

        coffeePrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        coffeePrice.setText("Price: 12.99");

        coffeeAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        coffeeAdd.setText("Add to cart");
        coffeeAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coffeeAddActionPerformed(evt);
            }
        });

        coffeeDes2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        coffeeDes2.setText("ethical practices in the supply chain");

        cutleryTitleLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cutleryTitleLbl.setText("Biodegrandable Cutlery");

        cutleryDesLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cutleryDesLbl.setText("An eco-alternative to plastic cutlery.");

        cutleryPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cutleryPrice.setText("Price: 3.99");

        cutleryAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cutleryAdd.setText("Add to cart");
        cutleryAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutleryAddActionPerformed(evt);
            }
        });

        cutleryTitleLbl1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cutleryTitleLbl1.setText("Orangic Cotton Jeans");

        jeansDes1Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jeansDes1Lbl.setText("A pair of jeans made from organic cotton, which is grown without ");

        jeansPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jeansPrice.setText("Price: 18.99");

        jeansAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jeansAdd.setText("Add to cart");
        jeansAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeansAddActionPerformed(evt);
            }
        });

        jeansDes2Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jeansDes2Lbl.setText("the use of synthetic pesticides or fertilzers");

        lightTitleLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lightTitleLbl.setText("LED Light Bulb");

        lightDes1Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lightDes1Lbl.setText("Energy Efficient light bulbs that las longer and consume less energy");

        lightDes2Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lightDes2Lbl.setText("that traditional bulbs.");

        lightPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lightPrice.setText("Price: 6.99");

        lightAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lightAdd.setText("Add to cart");
        lightAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightAddActionPerformed(evt);
            }
        });

        sBagTitlLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sBagTitlLbl.setText("Reusable Shopping Bag");

        sBagDes1Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sBagDes1Lbl.setText("Replace plastic bags with durable, reusable shopping bags made from");

        sBagDes2Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sBagDes2Lbl.setText("materials like cotton or jute");

        sBagPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sBagPrice.setText("Price: 2.49");

        sBagAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sBagAdd.setText("Add to cart");
        sBagAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sBagAddActionPerformed(evt);
            }
        });

        noteBookTitleLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        noteBookTitleLbl.setText("Sustainable Notebooks");

        noteBookDes1Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        noteBookDes1Lbl.setText("Notebooks made nfrom recycled or sustainably sourced paper, often");

        noteBookDes2Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        noteBookDes2Lbl.setText("with eco-friendly covers.");

        noteBookPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        noteBookPrice.setText("Price: 2.49");

        noteBookAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        noteBookAdd.setText("Add to cart");
        noteBookAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteBookAddActionPerformed(evt);
            }
        });

        fWashTitleLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fWashTitleLbl.setText("Organic & Natural Face Wash");

        fWashDes1Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fWashDes1Lbl.setText("A face wash made from organic and natural ingredients, minimizing the");

        fWashDes2Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fWashDes2Lbl.setText("use of synthetic chemicals");

        fWashPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fWashPrice.setText("Price: 7.99");

        fWashAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fWashAdd.setText("Add to cart");
        fWashAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fWashAddActionPerformed(evt);
            }
        });

        jewelryTitleLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jewelryTitleLbl.setText("Upcycled Jewelry");

        jewelryDes1Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jewelryDes1Lbl.setText("Jewelry made from repurposed materials, reducing the environmental");

        jewelryDes2Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jewelryDes2Lbl.setText("impact of mining");

        jewelryPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jewelryPrice.setText("Price: 19.99");

        jewelryAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jewelryAdd.setText("Add to cart");
        jewelryAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jewelryAddActionPerformed(evt);
            }
        });

        cCupTitleLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cCupTitleLbl.setText("Reusable Coffee Cups");

        cCupDes1Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cCupDes1Lbl.setText("Bring and use your own coffee cup everywhere to reduce the use of");

        cCupDes2Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cCupDes2Lbl.setText("disposable cups.");

        cCupPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cCupPrice.setText("Price: 8.99");

        cCupAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cCupAdd.setText("Add to cart");
        cCupAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCupAddActionPerformed(evt);
            }
        });

        trashBagsTitleLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        trashBagsTitleLbl.setText("Biodegradable Trash Bags");

        cCupDes1Lbl1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cCupDes1Lbl1.setText("Trash bags that braek down naturally, reducing plastic waste in landfills.");

        trashBagsPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        trashBagsPrice.setText("Price: 4.99");

        trashBagsAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        trashBagsAdd.setText("Add to cart");
        trashBagsAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trashBagsAddActionPerformed(evt);
            }
        });

        chargerTitleLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chargerTitleLbl.setText("Hybrid Solar Charger");

        chargerDes1Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chargerDes1Lbl.setText("Portable chargers that combine solar and traditional charging methods");

        chargerPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chargerPrice.setText("Price: 29.99");

        chargerAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chargerAdd.setText("Add to cart");
        chargerAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chargerAddActionPerformed(evt);
            }
        });

        chargerDes2lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chargerDes2lbl.setText("for increased efficiency.");

        binAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        binAdd.setText("Add to cart");
        binAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                binAddActionPerformed(evt);
            }
        });

        binTitleLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        binTitleLbl.setText("Compost Bin");

        binDes1Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        binDes1Lbl.setText("Containers designed for composting organic waste, yurning it into");

        binDes2Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        binDes2Lbl.setText("nutrient-rich compost for gardening.");

        binPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        binPrice.setText("Price: 39.99");

        shirtTitleLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        shirtTitleLbl.setText("Organic Cotton Shirt");

        shirtDes1Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        shirtDes1Lbl.setText("A T-shirt made from organic cotton, which is grown without the use");

        shirtDes2Lbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        shirtDes2Lbl.setText("of synthetic pesticides or fertilizers.");

        shirtPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        shirtPrice.setText("Price: 10.99");

        shirtAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        shirtAdd.setText("Add to cart");
        shirtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shirtAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(trashBagsLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jewelryLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(coffeeCupLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jewelryAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jewelryPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jewelryDes1Lbl)
                                        .addComponent(jewelryTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jewelryDes2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cCupAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cCupPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cCupDes1Lbl)
                                        .addComponent(cCupTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cCupDes2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(trashBagsAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(trashBagsPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cCupDes1Lbl1)
                                        .addComponent(trashBagsTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chargerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(chargerAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chargerPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chargerDes1Lbl)
                                    .addComponent(chargerTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chargerDes2lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nBooksLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(noteBookAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(noteBookPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(noteBookDes1Lbl)
                                    .addComponent(noteBookTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(noteBookDes2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fWashLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fWashAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fWashPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fWashDes1Lbl)
                                    .addComponent(fWashTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fWashDes2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(wBottleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bottleAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cartLbl)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(bottlePriceLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(bottleDesLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(bottleTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(toothAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(toothDesLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(toothDesTitle)
                                        .addComponent(toothTitlLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(coffeeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(coffeeDes2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(coffeePrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(coffeeDes1Lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(coffeeTitleLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sBagLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sBagAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sBagPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sBagDes1Lbl)
                                    .addComponent(sBagTitlLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sBagDes2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jeansLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cuttleryLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cutleryAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cutleryPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cutleryDesLbl)
                                    .addComponent(cutleryTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jeansAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jeansPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jeansDes1Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cutleryTitleLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jeansDes2Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lightLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(coffeeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(tBrushLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lightAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lightPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lightDes1Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lightTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lightDes2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(binLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(binAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(binPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(binDes1Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(binTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(binDes2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(shirtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(shirtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shirtPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(shirtDes1Lbl)
                            .addComponent(shirtTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shirtDes2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cartLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bottleTitleLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bottleDesLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bottlePriceLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bottleAdd)
                        .addGap(103, 103, 103)
                        .addComponent(toothTitlLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toothDesTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toothDesLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toothAdd))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(wBottleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tBrushLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coffeeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(coffeeTitleLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coffeeDes1Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coffeeDes2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coffeePrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coffeeAdd)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cuttleryLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(cutleryTitleLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cutleryDesLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cutleryPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cutleryAdd)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jeansLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(cutleryTitleLbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jeansDes1Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jeansDes2Lbl)
                        .addGap(4, 4, 4)
                        .addComponent(jeansPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jeansAdd)))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lightTitleLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lightDes1Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lightDes2Lbl)
                        .addGap(4, 4, 4)
                        .addComponent(lightPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lightAdd))
                    .addComponent(lightLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(sBagLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sBagTitlLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sBagDes1Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sBagDes2Lbl)
                        .addGap(4, 4, 4)
                        .addComponent(sBagPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sBagAdd)
                        .addGap(36, 36, 36)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nBooksLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(noteBookTitleLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noteBookDes1Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noteBookDes2Lbl)
                        .addGap(4, 4, 4)
                        .addComponent(noteBookPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noteBookAdd)
                        .addGap(16, 16, 16)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fWashLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(fWashTitleLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fWashDes1Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fWashDes2Lbl)
                        .addGap(4, 4, 4)
                        .addComponent(fWashPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fWashAdd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jewelryLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jewelryTitleLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jewelryDes1Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jewelryDes2Lbl)
                        .addGap(4, 4, 4)
                        .addComponent(jewelryPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jewelryAdd)
                        .addGap(42, 42, 42)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(coffeeCupLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cCupTitleLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cCupDes1Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cCupDes2Lbl)
                        .addGap(4, 4, 4)
                        .addComponent(cCupPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cCupAdd)
                        .addGap(44, 44, 44)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(trashBagsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(trashBagsTitleLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cCupDes1Lbl1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trashBagsPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trashBagsAdd)
                        .addGap(44, 44, 44)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chargerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(chargerTitleLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chargerDes1Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chargerDes2lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chargerPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chargerAdd)
                        .addGap(36, 36, 36)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(binLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(binTitleLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(binDes1Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(binDes2Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(binPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(binAdd)
                        .addGap(26, 26, 26)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shirtLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(shirtTitleLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shirtDes1Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shirtDes2Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shirtPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shirtAdd))))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout marketplacePnlLayout = new javax.swing.GroupLayout(marketplacePnl);
        marketplacePnl.setLayout(marketplacePnlLayout);
        marketplacePnlLayout.setHorizontalGroup(
            marketplacePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        marketplacePnlLayout.setVerticalGroup(
            marketplacePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, marketplacePnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        quizPnl.setBackground(new java.awt.Color(55, 162, 179));

        javax.swing.GroupLayout quizPnlLayout = new javax.swing.GroupLayout(quizPnl);
        quizPnl.setLayout(quizPnlLayout);
        quizPnlLayout.setHorizontalGroup(
            quizPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );
        quizPnlLayout.setVerticalGroup(
            quizPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(homePnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(242, Short.MAX_VALUE)
                    .addComponent(marketplacePnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(240, Short.MAX_VALUE)
                    .addComponent(quizPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homePnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(marketplacePnl, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 7, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(quizPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonPnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonPnlMouseClicked
        homePnl.setVisible(true);
        marketplacePnl.setVisible(false);
        quizPnl.setVisible(false);
    }//GEN-LAST:event_homeButtonPnlMouseClicked

    private void marketplaceButtonPnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marketplaceButtonPnlMouseClicked
// temporary measure
        homePnl.setVisible(false);
        marketplacePnl.setVisible(true);
        quizPnl.setVisible(false);
    }//GEN-LAST:event_marketplaceButtonPnlMouseClicked

    private void quizButtonPnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quizButtonPnlMouseClicked
        homePnl.setVisible(true);
        marketplacePnl.setVisible(false);
        quizPnl.setVisible(false);
        QuizGUI myQuiz;
        myQuiz = new QuizGUI();
        myQuiz.setVisible(true);
    }//GEN-LAST:event_quizButtonPnlMouseClicked

    private void eMobilityBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eMobilityBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eMobilityBtnActionPerformed

    private void metroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metroBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_metroBtnActionPerformed

    private void trainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trainBtnActionPerformed

    private void carBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_carBtnMouseClicked

    private void carBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nextBtnActionPerformed

    private void shirtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shirtAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shirtAddActionPerformed

    private void binAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_binAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_binAddActionPerformed

    private void chargerAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chargerAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chargerAddActionPerformed

    private void trashBagsAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trashBagsAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trashBagsAddActionPerformed

    private void cCupAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCupAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCupAddActionPerformed

    private void jewelryAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jewelryAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jewelryAddActionPerformed

    private void fWashAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fWashAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fWashAddActionPerformed

    private void noteBookAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteBookAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noteBookAddActionPerformed

    private void sBagAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sBagAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sBagAddActionPerformed

    private void lightAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lightAddActionPerformed

    private void jeansAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeansAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jeansAddActionPerformed

    private void cutleryAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutleryAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cutleryAddActionPerformed

    private void coffeeAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coffeeAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coffeeAddActionPerformed

    private void toothAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toothAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toothAddActionPerformed

    private void bottleAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottleAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bottleAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransitTraceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransitTraceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransitTraceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransitTraceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransitTraceGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton binAdd;
    private javax.swing.JLabel binDes1Lbl;
    private javax.swing.JLabel binDes2Lbl;
    private javax.swing.JLabel binLbl;
    private javax.swing.JLabel binPrice;
    private javax.swing.JLabel binTitleLbl;
    private javax.swing.JRadioButton bottleAdd;
    private javax.swing.JLabel bottleDesLbl;
    private javax.swing.JLabel bottlePriceLbl;
    private javax.swing.JLabel bottleTitleLbl;
    private javax.swing.JToggleButton busBtn;
    private javax.swing.JSpinner busSpnr;
    private javax.swing.JRadioButton cCupAdd;
    private javax.swing.JLabel cCupDes1Lbl;
    private javax.swing.JLabel cCupDes1Lbl1;
    private javax.swing.JLabel cCupDes2Lbl;
    private javax.swing.JLabel cCupPrice;
    private javax.swing.JLabel cCupTitleLbl;
    private javax.swing.JToggleButton carBtn;
    private javax.swing.JSpinner carSpnr;
    private javax.swing.JLabel cartLbl;
    private javax.swing.JRadioButton chargerAdd;
    private javax.swing.JLabel chargerDes1Lbl;
    private javax.swing.JLabel chargerDes2lbl;
    private javax.swing.JLabel chargerLbl;
    private javax.swing.JLabel chargerPrice;
    private javax.swing.JLabel chargerTitleLbl;
    private javax.swing.JRadioButton coffeeAdd;
    private javax.swing.JLabel coffeeCupLbl;
    private javax.swing.JLabel coffeeDes1Lbl;
    private javax.swing.JLabel coffeeDes2;
    private javax.swing.JLabel coffeeLbl;
    private javax.swing.JLabel coffeePrice;
    private javax.swing.JLabel coffeeTitleLbl;
    private javax.swing.JRadioButton cutleryAdd;
    private javax.swing.JLabel cutleryDesLbl;
    private javax.swing.JLabel cutleryPrice;
    private javax.swing.JLabel cutleryTitleLbl;
    private javax.swing.JLabel cutleryTitleLbl1;
    private javax.swing.JLabel cuttleryLbl;
    private javax.swing.JToggleButton eMobilityBtn;
    private javax.swing.JSpinner eMobilitySpnr;
    private javax.swing.JRadioButton fWashAdd;
    private javax.swing.JLabel fWashDes1Lbl;
    private javax.swing.JLabel fWashDes2Lbl;
    private javax.swing.JLabel fWashLbl;
    private javax.swing.JLabel fWashPrice;
    private javax.swing.JLabel fWashTitleLbl;
    private javax.swing.JPanel homeButtonPnl;
    private javax.swing.JLabel homeLbl;
    private javax.swing.JPanel homePnl;
    private javax.swing.JLabel homeTitleLbl;
    private javax.swing.JLabel instructionLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jeansAdd;
    private javax.swing.JLabel jeansDes1Lbl;
    private javax.swing.JLabel jeansDes2Lbl;
    private javax.swing.JLabel jeansLbl;
    private javax.swing.JLabel jeansPrice;
    private javax.swing.JRadioButton jewelryAdd;
    private javax.swing.JLabel jewelryDes1Lbl;
    private javax.swing.JLabel jewelryDes2Lbl;
    private javax.swing.JLabel jewelryLbl;
    private javax.swing.JLabel jewelryPrice;
    private javax.swing.JLabel jewelryTitleLbl;
    private javax.swing.JRadioButton lightAdd;
    private javax.swing.JLabel lightDes1Lbl;
    private javax.swing.JLabel lightDes2Lbl;
    private javax.swing.JLabel lightLbl;
    private javax.swing.JLabel lightPrice;
    private javax.swing.JLabel lightTitleLbl;
    private javax.swing.JPanel logoButtonPnl;
    private javax.swing.JLabel logoLbl;
    private javax.swing.JPanel marketplaceButtonPnl;
    private javax.swing.JLabel marketplaceLbl;
    private javax.swing.JPanel marketplacePnl;
    private javax.swing.JPanel menuPnl;
    private javax.swing.JToggleButton metroBtn;
    private javax.swing.JSpinner metroSpnr;
    private javax.swing.JToggleButton motorbikeBtn;
    private javax.swing.JSpinner motorbikeSpnr;
    private javax.swing.JLabel nBooksLbl;
    private javax.swing.JButton nextBtn;
    private javax.swing.JRadioButton noteBookAdd;
    private javax.swing.JLabel noteBookDes1Lbl;
    private javax.swing.JLabel noteBookDes2Lbl;
    private javax.swing.JLabel noteBookPrice;
    private javax.swing.JLabel noteBookTitleLbl;
    private javax.swing.JPanel quizButtonPnl;
    private javax.swing.JLabel quizLbl;
    private javax.swing.JPanel quizPnl;
    private javax.swing.JRadioButton sBagAdd;
    private javax.swing.JLabel sBagDes1Lbl;
    private javax.swing.JLabel sBagDes2Lbl;
    private javax.swing.JLabel sBagLbl;
    private javax.swing.JLabel sBagPrice;
    private javax.swing.JLabel sBagTitlLbl;
    private javax.swing.JRadioButton shirtAdd;
    private javax.swing.JLabel shirtDes1Lbl;
    private javax.swing.JLabel shirtDes2Lbl;
    private javax.swing.JLabel shirtLbl;
    private javax.swing.JLabel shirtPrice;
    private javax.swing.JLabel shirtTitleLbl;
    private javax.swing.JLabel tBrushLbl;
    private javax.swing.JRadioButton toothAdd;
    private javax.swing.JLabel toothDesLbl;
    private javax.swing.JLabel toothDesTitle;
    private javax.swing.JLabel toothTitlLbl;
    private javax.swing.JToggleButton trainBtn;
    private javax.swing.JSpinner trainSpnr;
    private javax.swing.JToggleButton tramBtn;
    private javax.swing.JSpinner tramSpnr;
    private javax.swing.JRadioButton trashBagsAdd;
    private javax.swing.JLabel trashBagsLbl;
    private javax.swing.JLabel trashBagsPrice;
    private javax.swing.JLabel trashBagsTitleLbl;
    private javax.swing.JLabel wBottleLbl;
    // End of variables declaration//GEN-END:variables
}
